openapi: 3.0.4
info:
  title: Book Tracker API
  version: 1.0.0
  description: API for tracking books in a personal library.
paths:
  /users:
    get:
      summary: Get all users
      operationId: getUsers
      responses:
        "200":
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDTO"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDTO"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
        "400":
          $ref: "./components/responses.yml#/components/responses/BadRequest"
        "409":
          $ref: "./components/responses.yml#/components/responses/Conflict"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: Get user by ID
      operationId: getUserById
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"
    put:
      summary: Update user by ID
      operationId: updateUserById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDTO"
      responses:
        "200":
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

    delete:
      summary: Delete user by id
      operationId: deleteUser
      responses:
        "204":
          description: User deleted successfully
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

  /books:
    get:
      summary: Get all books
      operationId: getBooks
      responses:
        "200":
          description: List of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BookDTO"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"
    post:
      summary: Create a new book
      operationId: createBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookDTO"
      responses:
        "201":
          description: Book created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookDTO"
        "400":
          $ref: "./components/responses.yml#/components/responses/BadRequest"
        "409":
          $ref: "./components/responses.yml#/components/responses/Conflict"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

  /books/search:
    get:
      summary: Search books by their attributes
      description: Search books by title, authors, ISBN, publisher, or language.
      operationId: searchBooks
      parameters:
        - name: title
          in: query
          description: Title or part of the title to search for
          schema:
            type: string
            example: "The Pragmatic Programmer"
        - name: authors
          in: query
          description: Author name or part of the name to search for
          schema:
            type: string
            example: "Andrew Hunt, David Thomas"
        - name: isbn
          in: query
          description: ISBN-10 or ISBN-13 to search for
          schema:
            type: string
            example: "978-013595705"
        - name: publisher
          in: query
          description: Publisher name or part of the name to search for
          schema:
            type: string
            example: "Pragmatic Programmer"
        - name: language
          in: query
          description: Language code to search for (e.g., "eng", "por")
          schema:
            type: string
            example: "por"
        - name : page
          in: query
          schema:
            type: integer
            default: 0
            minimum: 0
        - name : size
          in: query
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
      responses:
        "200":
          description: List of books matching the search criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BookDTO"
        "400":
          $ref: "./components/responses.yml#/components/responses/BadRequest"
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

  /books/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: Get book by ID
      operationId: getBookById
      responses:
        "200":
          description: Book found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookDTO"
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"
    put:
      summary: Update book by ID
      operationId: updateBookById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookDTO"
      responses:
        "200":
          description: Book updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookDTO"
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

    delete:
      summary: Delete book by id
      operationId: deleteBook
      responses:
        "204":
          description: Book deleted successfully
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"


components:
  schemas:
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
      required:
        - username
        - email

    BookDTO:
      type: object
      required:
        - title
        - authors
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        authors:
          type: array
          items:
            type: string
        isbn:
          type: string
          description: "Optional ISBN-10 or ISBN-13. Normalized to ISBN-13 internally if provided."
        publisher:
          type: string
        language:
          type: string
          example: "por"
        pages:
          type: integer
          minimum: 1
        coverImageUrl:
          type: string
          format: uri
