openapi: 3.0.4
info:
  title: Book Tracker API
  version: 1.0.0
  description: API for tracking books in a personal library.
paths:
  /users:
    get:
      summary: Get all users
      operationId: getUsers
      tags:
        - Users
      responses:
        "200":
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./components/schemas.yml#/UserDTO"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

    post:
      summary: Create a new user
      operationId: createUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas.yml#/UserDTO"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "./components/schemas.yml#/UserDTO"
        "400":
          $ref: "./components/responses.yml#/components/responses/BadRequest"
        "409":
          $ref: "./components/responses.yml#/components/responses/Conflict"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: Get user by ID
      operationId: getUserById
      tags:
        - Users
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: "./components/schemas.yml#/UserDTO"
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"
    put:
      summary: Update user by ID
      operationId: updateUserById
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas.yml#/UserDTO"
      responses:
        "200":
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: "./components/schemas.yml#/UserDTO"
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

    delete:
      summary: Delete user by id
      operationId: deleteUser
      tags:
        - Users
      responses:
        "204":
          description: User deleted successfully
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

  /users/{id}/readings:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: Get user with their readings by user ID
      operationId: getUserWithReadings
      tags:
        - Users
      responses:
        "200":
          description: User with readings found
          content:
            application/json:
              schema:
                $ref: "./components/schemas.yml#/UserWithReadingsDTO"
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"
    post:
      summary: Add a reading to a user
      operationId: addReadingToUser
      tags:
        - Readings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas.yml#/ReadingDto"
      responses:
        "201":
          description: Reading added successfully
          content:
            application/json:
              schema:
                $ref: "./components/schemas.yml#/ReadingDto"
        "400":
          $ref: "./components/responses.yml#/components/responses/BadRequest"
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"
  /users/{userId}/readings/{readingId}:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: readingId
        in: path
        required: true
        schema:
          type: integer
          format: int64
    delete:
      summary: Delete a reading from a user
      operationId: deleteReadingFromUser
      tags:
        - Readings
      responses:
        "204":
          description: Reading deleted successfully
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"
    get:
      summary: Get a specific reading of a user
      operationId: getReadingOfUser
      tags:
        - Readings
      responses:
        "200":
          description: Reading found
          content:
            application/json:
              schema:
                $ref: "./components/schemas.yml#/ReadingDto"
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"
    patch:
      summary: Update a specific reading of a user
      operationId: updateReadingOfUser
      tags:
        - Readings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas.yml#/ReadingDto"
      responses:
        "200":
          description: Reading updated successfully
          content:
            application/json:
              schema:
                $ref: "./components/schemas.yml#/ReadingDto"
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

  /users/{userId}/readings/{readingId}/complete:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: readingId
        in: path
        required: true
        schema:
          type: integer
          format: int64
    post:
      summary: Mark a reading as complete for a user
      operationId: completeReadingForUser
      tags:
        - Readings
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "./components/schemas.yml#/FinishReadingRequest"
      responses:
        "200":
          description: Reading marked as complete successfully
          content:
            application/json:
              schema:
                $ref: "./components/schemas.yml#/ReadingDto"
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

  /books:
    get:
      summary: Get all books
      operationId: getBooks
      tags:
        - Books
      responses:
        "200":
          description: List of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./components/schemas.yml#/BookDTO"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"
    post:
      summary: Create a new book
      operationId: createBook
      tags:
        - Books
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas.yml#/BookDTO"
      responses:
        "201":
          description: Book created successfully
          content:
            application/json:
              schema:
                $ref: "./components/schemas.yml#/BookDTO"
        "400":
          $ref: "./components/responses.yml#/components/responses/BadRequest"
        "409":
          $ref: "./components/responses.yml#/components/responses/Conflict"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

  /books/search:
    get:
      summary: Search books by their attributes
      description: Search books by title, authors, ISBN, publisher, or language.
      operationId: searchBooks
      tags:
        - Books
      parameters:
        - name: title
          in: query
          description: Title or part of the title to search for
          schema:
            type: string
            example: "The Pragmatic Programmer"
        - name: authors
          in: query
          description: Author name or part of the name to search for
          schema:
            type: string
            example: "Andrew Hunt, David Thomas"
        - name: isbn
          in: query
          description: ISBN-10 or ISBN-13 to search for
          schema:
            type: string
            example: "978-013595705"
        - name: publisher
          in: query
          description: Publisher name or part of the name to search for
          schema:
            type: string
            example: "Pragmatic Programmer"
        - name: language
          in: query
          description: Language code to search for (e.g., "eng", "por")
          schema:
            type: string
            example: "por"
        - name : page
          in: query
          schema:
            type: integer
            default: 0
            minimum: 0
        - name : size
          in: query
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
      responses:
        "200":
          description: List of books matching the search criteria
          content:
            application/json:
              schema:
                $ref: "./components/schemas.yml#/BookPage"
        "400":
          $ref: "./components/responses.yml#/components/responses/BadRequest"
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

  /books/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: Get book by ID
      operationId: getBookById
      tags:
        - Books
      responses:
        "200":
          description: Book found
          content:
            application/json:
              schema:
                $ref: "./components/schemas.yml#/BookDTO"
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"
    put:
      summary: Update book by ID
      operationId: updateBookById
      tags:
        - Books
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas.yml#/BookDTO"
      responses:
        "200":
          description: Book updated successfully
          content:
            application/json:
              schema:
                $ref: "./components/schemas.yml#/BookDTO"
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"

    delete:
      summary: Delete book by id
      operationId: deleteBook
      tags:
        - Books
      responses:
        "204":
          description: Book deleted successfully
        "404":
          $ref: "./components/responses.yml#/components/responses/NotFound"
        "500":
          $ref: "./components/responses.yml#/components/responses/InternalServerError"
